const userActionTypes = {
  LOG_IN_START: 'LOG_IN_START',
  LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
  LOG_IN_FAILURE: 'LOG_IN_FAILURE',
  LOG_OUT: 'LOG_OUT',

  GET_DELIVERY_START: 'GET_DELIVERY_START',
  GET_DELIVERY_SUCCESS: 'GET_DELIVERY_SUCCESS',
  GET_DELIVERY_FAILURE: 'GET_DELIVERY_FAILURE',

  GET_EVENTS_START: 'GET_EVENTS_START',
  GET_EVENTS_SUCCESS: 'GET_EVENTS_SUCCESS',
  GET_EVENTS_FAILURE: 'GET_EVENTS_FAILURE',

  CREATE_EVENT_START: 'CREATE_EVENT_START',
  CREATE_EVENT_SUCCESS: 'CREATE_EVENT_SUCCESS',
  CREATE_EVENT_FAILURE: 'CREATE_EVENT_FAILURE',

  UPDATE_EVENT_START: 'UPDATE_EVENT_START',
  UPDATE_EVENT_SUCCESS: 'UPDATE_EVENT_SUCCESS',
  UPDATE_EVENT_FAILURE: 'UPDATE_EVENT_FAILURE',

  DELETE_EVENT_START: 'DELETE_EVENT_START',
  DELETE_EVENT_SUCCESS: 'DELETE_EVENT_SUCCESS',
  DELETE_EVENT_FAILURE: 'DELETE_EVENT_FAILURE',

  GET_TEMPLATE_START: 'GET_TEMPLATE_START',
  GET_TEMPLATE_SUCCESS: 'GET_TEMPLATE_SUCCESS',
  GET_TEMPLATE_FAILURE: 'GET_TEMPLATE_FAILURE',

  CREATE_TEMPLATE_START: 'CREATE_TEMPLATE_START',
  CREATE_TEMPLATE_SUCCESS: 'CREATE_TEMPLATE_SUCCESS',
  CREATE_TEMPLATE_FAILURE: 'CREATE_TEMPLATE_FAILURE',

  UPDATE_TEMPLATE_START: 'UPDATE_TEMPLATE_START',
  UPDATE_TEMPLATE_SUCCESS: 'UPDATE_TEMPLATE_SUCCESS',
  UPDATE_TEMPLATE_FAILURE: 'UPDATE_TEMPLATE_FAILURE',

  DELETE_TEMPLATE_START: "DELETE_TEMPLATE_START",
  DELETE_TEMPLATE_SUCCESS: "DELETE_TEMPLATE_SUCCESS",
  DELETE_TEMPLATE_FAILURE: "DELETE_TEMPLATE_FAILURE",

  GET_RULES_START: "GET_RULES_START",
  GET_RULES_SUCCESS: "GET_RULES_SUCCESS",
  GET_RULES_FAILURE: "GET_RULES_FAILURE",

  GET_LOOKUP_START: "GET_LOOKUP_START",
  GET_LOOKUP_SUCCESS: "GET_LOOKUP_SUCCESS",
  GET_LOOKUP_FAILURE: "GET_LOOKUP_FAILURE",

  CREATE_RULE_START: "CREATE_RULE_STATR",
  CREATE_RULE_SUCCESS: "CREATE_RULE_SUCCESS",
  CREATE_RULE_FAILURE: "CREATE_RULE_FAILURE",

  UPDATE_RULE_START: "UPDATE_RULE_START",
  UPDATE_RULE_SUCCESS: "UPDATE_RULE_SUCCESS",
  UPDATE_RULE_FAILURE: "UPDATE_RULE_FAILURE",

  GET_CUSTOMER_START: "GET_CUSTOMER_START",
  GET_CUSTOMER_SUCCESS: "GET_CUSTOMER_SUCCESS",
  GET_CUSTOMER_FAILURE: "GET_CUSTOMER_FAILURE",

  CREATE_CUSTOMER_START: "CREATE_CUSTOMER_START",
  CREATE_CUSTOMER_SUCCESS: "CREATE_CUSTOMER_SUCCESS",
  CREATE_CUSTOMER_FAILURE: "CREATE_CUSTOMER_FAILURE",

  UPDATE_CUSTOMER_START: "UPDATE_CUSTOMER_START",
  UPDATE_CUSTOMER_SUCCESS: "UPDATE_CUSTOMER_SUCCESS",
  UPDATE_CUSTOMER_FAILURE: "UPDATE_CUSTOMER_FAILURE",

  GET_STORAGE_START: "GET_STORAGE_START",
  GET_STORAGE_SUCCESS: "GET_STORAGE_SUCCESS",
  GET_STORAGE_FAILURE: "GET_STORAGE_FAILURE",

  GET_POOL_PROVIDER_START: 'GET_POOL_PROVIDER_START',
  GET_POOL_PROVIDER_SUCCESS: 'GET_POOL_PROVIDER_SUCCESS',
  GET_POOL_PROVIDER_FAILURE: 'GET_POOL_PROVIDER_FAILURE',

  GET_BROKER_START: 'GET_BROKER_START',
  GET_BROKER_SUCCESS: "GET_BROKER_SUCCESS",
  GET_BROKER_FAILURE: "GET_BROKER_FAILURE",

  CREATE_BROKER_START: "CREATE_BROKER_START",
  CREATE_BROKER_SUCCESS: "CREATE_BROKER_SUCCESS",
  CREATE_BROKER_FAILURE: "CREATE_BROKER_FAILURE",

  UPDATE_BROKER_START: "UPDATE_BROKER_START",
  UPDATE_BROKER_SUCCESS: "UPDATE_BROKER_SUCCESS",
  UPDATE_BROKER_FAILURE: "UPDATE_BROKER_FAILURE",

  GET_PERMISSION_START: "GET_PERMISSION_START",
  GET_PERMISSION_SUCCESS: "GET_PERMISSION_SUCCESS",
  GET_PERMISSION_FAILURE: "GET_PERMISSION_FAILURE",

  CREATE_PERMISSION_START: 'CREATE_PERMISSION_START',
  CREATE_PERMISSION_SUCCESS: 'CREATE_PERMISSION_SUCCESS',
  CREATE_PERMISSION_FAILURE: 'CREATE_PERMISSION_FAILURE',

  UPDATE_PERMISSION_START: 'UPDATE_PERMISSION_START',
  UPDATE_PERMISSION_SUCCESS: 'UPDATE_PERMISSION_SUCCESS',
  UPDATE_PERMISSION_FAILURE: "UPDATE_PERMISSION_FAILURE",

  GET_DEPARTMENT_START: 'GET_DEPARTMENT_START',
  GET_DEPARTMENT_SUCCESS: 'GET_DEPARTMENT_SUCCESS',
  GET_DEPARTMENT_FAILURE: 'GET_DEPARTMENT_FAILURE',

    // PURCHASE INVOICE

    GET_PURCHASE_START: 'GET_PURCHASE_START',
    GET_PURCHASE_SUCCESS: 'GET_PURCHASE_SUCCESS',
    GET_PURCHASE_FAILURE: 'GET_PURCHASE_FAILURE',
  
    CREATE_PURCHASE_START: 'CREATE_PURCHASE_START',
    CREATE_PURCHASE_SUCCESS: 'CREATE_PURCHASE_SUCCESS',
    CREATE_PURCHASE_FAILURE: 'CREATE_PURCHASE_FAILURE',
  
    UPDATE_PURCHASE_START: 'UPDATE_PURCHASE_START',
    UPDATE_PURCHASE_SUCCESS: 'UPDATE_PURCHASE_SUCCESS',
    UPDATE_PURCHASE_FAILURE: 'UPDATE_PURCHASE_FALIURE',
  
    DELETE_PURCHASE_START: 'DELETE_PURCHASE_START',
    DELETE_PURCHASE_SUCCESS: 'DELETE_PURCHASE_SUCCESS',
    DELETE_PURCHASE_FAILURE: 'DELETE_PURCHASE_FALIURE',
  
};

export default userActionTypes;

