export const corporateOfficeInitialValue = {
    Entity_Type_Id: 3,
    id: 0,
    LegalName: "",
    SCAC: "",
    dbaName: "",
    Type: "Broker",
    MC_Number: "",
    IsW9_YN: false,
    DOT_Number: "",
    DUNS_Number: "",
    Federal_Tax_ID: "",
    IsActive: true,
    IsCarrier: false,
    IsDeleted: false,
    IsEdi: false,
    IsEntityAdmin: false,
    Comments: "",
    Fax: "",
    City: "",
    Phone: "",
    State: "",
    Zipcode: "",
    Address1: "",
    Address2: "",
    Id: 0,

}
export const initalValueBill = {
    ContactEmail: "",
    ContactName: "",
    ContactPhone: "",
    Type: "",
    Terms: "",
    IsActive: true,
    Comments: "",
    Fax: "",
    City: "",
    Phone: "",
    State: "",
    Zipcode: "",
    Address1: "",
    Address2: "",

}
export const initalValuepay = {
    ContactEmail: "",
    ContactName: "",
    ContactPhone: "",
    Type: "",
    Terms: "",
    IsActive: true,
    Comments: "",
    Fax: "",
    City: "",
    Phone: "",
    State: "",
    Zipcode: "",
    Address1: "",
    Address2: "",
}
export const contact = {
    Name: "",
    Type: "",
    Email: "",
    Phone: "",
    Title: "",
    Mobile: "",
    IsActive: true,
    Entity_Id: 2141,
    Extension: "",
    IsDeleted: false,
    Entity_Type: 1,
    Department_Id: "",
    IsSendInviteEmail: "false"
};